export type Md2PaletteType =
  'primary' |
  'primary-variant' |
  'secondary' |
  'secondary-variant' |
  'background' |
  'surface' |
  'error' |
  'success' |
  'warning' |
  'on-primary' |
  'on-secondary' |
  'on-background' |
  'on-surface' |
  'on-error' |
  'border' |
  'red' |
  'red-variant' |
  'pink' |
  'pink-variant' |
  'purple' |
  'purple-variant' |
  'deep-purple' |
  'deep-purple-variant' |
  'indigo' |
  'indigo-variant' |
  'blue' |
  'blue-variant' |
  'light-blue' |
  'light-blue-variant' |
  'cyan' |
  'cyan-variant' |
  'teal' |
  'teal-variant' |
  'green' |
  'green-variant' |
  'light-green' |
  'light-green-variant' |
  'lime' |
  'lime-variant' |
  'yellow' |
  'yellow-variant' |
  'amber' |
  'amber-variant' |
  'orange' |
  'orange-variant' |
  'deep-orange' |
  'deep-orange-variant' |
  'brown' |
  'brown-variant' |
  'grey' |
  'grey-variant' |
  'grey-blue' |
  'grey-blue-variant' |
  'white' |
  'black'
