export type Md2PaletteType =
  'primary' |
  'primaryVariant' |
  'secondary' |
  'secondaryVariant' |
  'background' |
  'surface' |
  'error' |
  'success' |
  'warning' |
  'onPrimary' |
  'onSecondary' |
  'onBackground' |
  'onSurface' |
  'onError' |
  'border' |
  'red' |
  'redVariant' |
  'pink' |
  'pinkVariant' |
  'purple' |
  'purpleVariant' |
  'deepPurple' |
  'deepPurpleVariant' |
  'indigo' |
  'indigoVariant' |
  'blue' |
  'blueVariant' |
  'lightBlue' |
  'lightBlueVariant' |
  'cyan' |
  'cyanVariant' |
  'teal' |
  'tealVariant' |
  'green' |
  'greenVariant' |
  'lightGreen' |
  'lightGreenVariant' |
  'lime' |
  'limeVariant' |
  'yellow' |
  'yellowVariant' |
  'amber' |
  'amberVariant' |
  'orange' |
  'orangeVariant' |
  'deepOrange' |
  'deepOrangeVariant' |
  'brown' |
  'brownVariant' |
  'grey' |
  'greyVariant' |
  'greyBlue' |
  'greyBlueVariant' |
  'white' |
  'black'
